name: "Setup and install pnpm"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.2.0
    - uses: actions/setup-node@v6.2.0
      with:
        node-version: 24
        cache: "pnpm"

    - shell: bash
      run: pnpm install
